function Settings() {}

Settings.BUTTON_GREEN_LINE = 0x00ff99;
Settings.BUTTON_YELLOW_LINE = 0xfeeb77;
Settings.CANVAS_WIDTH = 700;
Settings.CANVAS_HEIGHT = 500;
Settings.SPRITESHEET = "./images/icons-sheet.json";
Settings.EXPLOSION_SPRITE = "./images/explosion.json";

Settings.PLAYER_INITIAL_POSITION = 50;
Settings.PLAYER_SPEED = 10.7;
Settings.PLAYER_INITIAL_HEALTH = 100;
Settings.PLAYER_POINTS_ADDED_FOR_KILLED_ALIEN = 15;

Settings.ALIENS_INITIAL_X_POSITION = 50;
Settings.ALIENS_INITIAL_Y_POSITION = 100;

Settings.ALIEN_H_MARGIN = 30;
Settings.ALIEN_VERTICAL_MARGIN = 35;
Settings.ALIEN_AVAILABLE_PATTERNS = 7;
Settings.ALIEN_SHOOT_EACH_X_FRAMES = 20;

Settings.BULLET_LIFE_COST = 10;

Settings.HEALTH_BAR_WIDTH = 150;
Settings.HEALTH_BAR_HEIGHT = 20;
Settings.HEALTH_BAR_BORDER = 1;
